### ISSUE TITLE
Embedding hyperledger fabric into docker containers.

### ISSUE THREAD

**Issue by lu562** [jcs47/hyperledger-bftsmart#14]
Hi,
Do you have experience on importing the modified hyperledger fabric into some docker image so that we can use them just like the images provided by IBM? I'm just curious what should be put into the docker image to achieve this.

Thanks a lot :)

**Comment by jcs47** [comment]
Unfortunately I never ported this code to docker, but I am going to help a faculty colleague to do exactly that. Once we figured out how to do it or have our own images available, I'll let you know. Unfortunately, I'll be travelling this upcoming week, so I won't be able to make progress on this for a couple of days.

**Comment by lu562** [comment]
Hi, I found the method to import modified hyperledger fabric binaries into docker image. And it is pretty straight forward. After building modified hyperledger:
`cd fabric/build/image/peer/`
`docker build -t your_image_name .`

For now I haven't met any bug, if there is more information I will post it here.

**Comment by lu562** [comment]
So now I imported your hyperledger into containers (for orderer container to work, I mount /tmp/hlf-pool.sock into the container, I have no idea if this is right or not) and tried to test it. The case is that when I use "cli" container to send channel create request, orderer gave this error which did not make sense to me:
`2018-06-26 21:46:37.962 UTC [orderer/common/broadcast] Handle -> DEBU 2f7 [channel: mychannel] Broadcast has successfully enqueued message of type CONFIG_UPDATE from 172.22.0.6:41988
2018-06-26 21:46:37.966 UTC [common/deliver] deliverBlocks -> DEBU 2f8 Rejecting deliver for 172.22.0.6:41986 because channel mychannel not found
`

It said the channel could not be found but my request is a channel creation request for that channel name.....

**Comment by jcs47** [comment]
As I said I am currently travelling, so I can't look into this issue this week. However, I noticed you are building the ./peer program, but bear in mind that our fork modifies the orderer and configtxgen process. Use the command `grep -rl "JCS" ./` while on the root fabric directory to check out what was modified by us and thus what new images should be generated.

**Comment by lu562** [comment]
Thanks for reply when traveling. Yes indeed I create both "peer" image and "orderer" and I used modified "configgen" to generate genesis block and channel create tx. Here one thing I'm confused about is that for the bft-smart node you also bind it with some certificates in sampleconfig folder, while after checking they are actually certificates for peers. Is there any relation? what should I put on the sampleconfig folder if I created my own certificates for all identities? 

Thanks. I guess if this step passes, we would have working image for modified hyperledger.

**Comment by jcs47** [comment]
The sampleconfig folder is provided by default with the original hyperledger codebase, and it is set up with a single organization that is used for both the orderer, peers, and users. If you create your own certificates and identities using cryptogen and a different configtx.yaml file, then there is no point in using that folder anymore. But you do have to re-declare the $FABRIC_CFG_PATH to point the configtx.yaml file you are using to generate the new crypto material.

One thing I remembered is, are you mounting the orderer and java process in the same container (/fabric/orderer/orderer and /hyperledger-bftsmart/startFrontend.sh)? These processes must execute in the same machine because they communicate using UNIX sockets (which is what the /tmp/hlf-pool.sock is used for). Hence, I imagine they must also execute inside the same container. You'll also need to properly set the $FABRIC_CFG_PATH environment variable in each container (which if you didn't generate new crypto material, should still be the sampleorg folder)

**Comment by lu562** [comment]
Oh I see, OK I will try to mount java process into container and try again.

And regarding the first question, actually what I want to ask is that why the java process needs these certificates. Since when I tested, if I delete the folder "msp" in sampleconfig, I failed to start java process with the error message like "could not find 'key.pem'". 

Thanks.

**Comment by lu562** [comment]
Hi, this time I imported all java components into orderer image and made it run "normally". But when I use "cli" container to send channel create request, orderer still gave this error which did not make sense to me: `orderer.example.com       | 2018-07-20 20:50:55.714 UTC [common/deliver] deliverBlocks -> DEBU c9b Rejecting deliver for 172.25.0.6:60418 because channel mychannel not found
`.
Do you have some progress on this?
Thanks.

**Comment by jcs47** [comment]
Sorry for the very late reply. I've been busy implementing a lot of stuff into the ordering service (you might have noticed a very large commit to this repo last week).

I have finally created docker images for this ordering service. The readme file already contains instructions on how to deploy the system with docker containers, comprised by 4 ordering nodes, one frontend and a single peer (check the "quick start" section at the beginning). Instructions focusing on how to deploy containers in a real distributed environment are also coming soon.

**Comment by lu562** [comment]
Wow that's a great work. Thanks a lot. 

While just for curiosity, may I know what you put into the "frontend" container? I guess frontend java component and orderer binary have to be there? Is there anything else and is there any configuration we need to care about? Since sooner or later I think I will also need to modify some hyperledger code and build up my own image, so I will appreciate it a lot if you can share some points where we need to take care of when building new images. 

Thanks a lot.

**Comment by jcs47** [comment]
Yes, the contents of the frontend container are the orderer binary and the java component. I already updated the README with instructions on how to launch the same basic setup in a distributed enviroment using the docker swarm. As for stuff that needs to be taken care about, I will update the README with instructions on how to launch a network with more components and organizations. But the updated README already dwelves into a strange idiosyncrasy at the peer that happens with the swarm.

If you indeed anticipate having to build new images and fiddling with Fabric's code, you might want to check the script at ./docker_images/create-docker.images.sh. It is the script I use to build the images in the repository, and one thing that it does is to create an auxiliary image where my Fabric fork is compiled, so that might be of interest to you. Also, don't forget to pull the lastest versions of the images, that are now tagged `x86_64-1.1.1`
