### ISSUE TITLE
TPS problem

### ISSUE THREAD

**Issue by dzqoo** [jcs47/hyperledger-bftsmart#19]
Hello！
Recently，I use the bft-smart in my fabric network and my fabric is depolied with k8s.
But something is confusing me. I only got 150 tps while invoking and 1500 tps while quering,which is far less than the tps in your paper.I wonder what is wrong with the result.My k8s is builded under calico network and my test tools is caliper.

Looking forward your reply!

**Comment by jcs47** [comment]
Hi there,

I am not sure how you are producing workload, but the way we did it for that paper was to issue heavy loads directly at the ordering nodes, using special java clients to emulate the behavior of frontends issuing heavy workloads. Moreover, these results were produced with the ordering nodes only, not with a full Fabric depolyment. I just published a wiki page [explaining how to use that client to create workload]( https://github.com/bft-smart/fabric-orderingservice/wiki/Generating-workload-and-measurements).

Furthermore, bear in mind the evaluation presented in the paper was conducted with transactions of type "random", because at the time the ordering service did not have envelope validation implemented (make sure to properly configure the ordering nodes, as explained in the wiki page). Furthermore, the tests were conducted with the ordering nodes set to generate only one block signature instead of the two signatures that the default Fabric codebase generates (this can be enabled/disabled at the BOTH_SIGS parameter). If you want to try to achieve results close to the paper, you'll need to take this into consideration.

Alternitively, you can also use the sample clients that are mentioned in [our quick start guide (step \#10)](https://github.com/bft-smart/fabric-orderingservice/wiki/Quick-start).  For that case you can use actual frontends to produce throughput measurements, but bear in mind that since they use UNIX sockets to relay envelopes to the java component, you'll need to deploy several frontends and issue workloads at each one of them to overcome the bottleneck that is associated to the sockets.

**Comment by dzqoo** [comment]
Thanks  for your apply！This is really helpful！
