### ISSUE TITLE
Error after broadcast_timestamp

### ISSUE THREAD

**Issue by sa4152** [jcs47/hyperledger-bftsmart#3]
I followed the steps in the instruction, and got the 4 replicas, the proxy, and the orderer to work. But running  orderer/sample_clients/broadcast_timestamp/broadcast_timestamp --secure --messages 3 gave me an error in the proxy.
<img width="788" alt="2017-10-31 14 56 08" src="https://user-images.githubusercontent.com/33111399/32209597-44e75850-be4c-11e7-979f-62bd3c2da11a.png">
What does this mean? Or, what does the last tow commands (deliver_stdout & broadcast_timestamp) do in the first place?

**Comment by jcs47** [comment]
I never stumbled upon this ZMQ exception before, but judging from previous experience with BFT-SMaRt benchmarks, I suspect the cause is that you exceed the limit of open file descriptors. Try doing one, or both of these:

a)  Reduce the number of pooled connections by editing the ./orderer/orderer.yaml file, at the ConnectionPoolSize field in the BFTsmart section.

b) Before launching either the replicas or the proxy, increase the aforementioned file limit by typing `ulimit -n 10000` in the command line

**Comment by sa4152** [comment]
I followed the suggestion, then the error in proxy didn't appear but in the order
<img width="1420" alt="2017-11-01 13 52 22" src="https://user-images.githubusercontent.com/33111399/32260688-d7ac41da-bf0c-11e7-83e0-6c2e7486a123.png">
I'm not sure if this wasn't happening before, though.

**Comment by jcs47** [comment]
try creating this global variable before launching the whole system: `export ORDERER_CFG_PATH=<path to the fabric fork>`

Also make sure you are invoking the orderer from the main fabric folder, using `orderer/orderer`

**Comment by sa4152** [comment]
For some reason, the error didn't appear when I tried today. 

Setting ORDERER_CFG_PATH gave an error perhaps because it is obsolete? Setting the variable gave me the error described at the bottom of 
http://fabric-hlj.readthedocs.io/en/v1.0.0-alpha2/getting_started.html
'Unsupported...'

**Comment by jcs47** [comment]
Strange, I don't get that error, even using the latest HLF codebase. Even without having that variable set, the orderer still goes to the correct folder.
