### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by sa4152** [jcs47/hyperledger-bftsmart#4]
I am trying to understand how this ordering service fits into the standard HLF architecture. I mean, how it replaces the usual orderer (as a docker image).

Figure 5 of the referred paper gives some idea but I'm not sure about the following points:
1. What is specifically HLF SDK in Frontend and ordering nodes?
2. Does HLF consenter mean the orderer? If not, where a client send a proposal?
3. What kind of Byzantine situation is assumed? Is this component supposed to make an orderer service that consists of  not totally trustable orderers?
4. Related to 3, this doesn't make HLF tolerant to byzantine peers. Is this correct?

**Comment by jcs47** [comment]
1. the HLF SDK is a java library created by the hyperledger project that provides java implementations of the data structures used by the HLF codebase, as well as cryptographic services that are compatable to that aforementioned platform. For example, it provides a Block java implementations that is equivalent to its Go counterpart, and provides means to properly serialize/deserialize these data structures to make sure they are still compatible with the rest of the HLF framework.

2. An HLF consenter is supposed to be the Go interface that represents the orderer type (e.g., either the solo orderer, the kakfka orderer, or this one).

3. Yes, but the one thing that isn't clear in the paper is the fact that a proxy (i.e., the combined codebase of the Go orderer process and the BFTProxy java process) is supposed to share the same trusted domain with at least one ordering nodes (i.e., a BFT replica java process). What this essencially means is that if the proxy in trusted domain A is Byzantine, so is/are the ordering node(s) of trusted domain A (and vice versa).

4. Not entirely sure if I understand the question. If you are asking if this ordering service is tolerant to Byzantine fault, it is. If you are asking about the whole HLF framework, I would say that the developers of HLF are better equipped to answer this question than we are, because our focus was in developing a BFT ordering service. We never got to properly audit the rest of the platform and its general protocol.

**Comment by sa4152** [comment]
Thanks for the detailed answer.

Further question on 4. Sorry about being offtopic a bit.

In the HLF consensus process, a client collects signatures from endorsing peers and then sends it to the orderer. I suppose it is possible that endorsing peers are Byzantine. (What I meant by 'Byzantine peers' is Byzantine endorsing peers.) 

HLF-bftsmart does not handle such a situation, doesn't it?

**Comment by jcs47** [comment]
Correct, it doesn't handle such situation, but from what I understand from the HLF protocol, it doesn't have to. All the ordering service is required to do is to establish a total order on transactions across the system. It is the rest of the HLF protocol that is responsible for handling Byzantine peers, I believe. Again, this is a question that is more suitable for the developers of HLF.

**Comment by sa4152** [comment]
Thanks. 

Of course, I understand the situation I mentioned is out of scope for this component, but I was wondering in terms of the Byzantine tolerance of the whole hlf system.
