### ISSUE TITLE
How to get commandInfo requested before?

### ISSUE THREAD

**Issue by manxiaqu** [jcs47/hyperledger-bftsmart#5]
Here is the background of the problem:
I have start four replica、four proxy,three orderer(config four and start three) and set f=1;(I change some code of the hyperledger-bftsmart, and i use the master branch)
And I just do "create channel、install chaincode,instantiate chaincode,invoke request';and they just work well.
But when i start the fouth orderer, it can't Synchronize it's block to other orderer's block. 
So my question is . if a orderer stop for a long time and restart. how to Synchronize it's state to the other normal orderer?

And up to now, I try to get the request that the other orderer send before, and send it to the orderer which is just start. I try the function getstate and so on ,But i can't solve it .

**Comment by jcs47** [comment]
If I understood correctly, you are starting up the system with 4 replicas and 3 orderers/proxies, you then start issuing transactions to the system, and then midway through the system lifestan you want to activate a 4th orderer/proxy. Unfortunately this current codebase doesn't support that usecase yet, but we are currently working on adding functionality to support just that.

As for the function getState, are you refering to something in the original HLF framework, or the getstate function from the BFT-SMaRt codebase?

**Comment by manxiaqu** [comment]
Yeah, That's exactly what' i mean. And I try to use some function like getState、setState in the BFT-Smart codebase to get the state saved or command before.

First, I try to use getState(cid, sendState) method to get the saved state before on ServiceReplica. But I just get null when i use getSerializedState(). Then I think the reason i can't get the state is i don't save or set the state, which is definitely not right. So i Just try setstate() in appExecuteBatch(),and get Into the infinite loop.

Then, I try to get the commandInfo the orderers invoked before. In my opinoin, the BFT-Smart will save the commands so it can Synchronize  to state of the other normal replicas when the some replica restarted and reconnect to the communication system. But I can't get fix it out no matter how many times i tried.

So is there any method or way i can do to get the state or commands before in the BFT-Smart?

**Comment by jcs47** [comment]
First off, you need to know that developers are not supposed to use the getstate/setstate methods at all. Those are methods meant to be used internally by the library. You are only supposed to make implementations for each of them so that the library knows how to serialize/deserialise the state of the application that is built on top of the library, but they are not supposed to be invoked in any other context. The most recent commits to master branch already have  that serialization implemented for the state maintained at the replicas.

Secondly, those methods are meant for transfer state amongst replicas, but not proxies/orderers. Even if serialization is implemented for the replicas, you wouldn't be able to perform a state transfer among proxies/orderers. 

Finally, even among replicas, the codebase is still not ready for the addition of new replicas to the system, because the BFTProxy object isn't prepared yet to parse notifications about updates to the current view. The upcoming commits to the master branch will solve this problem, and they will probably happen this upcoming week. That will make the codebase able to support reconfigurations to the replicas. After that, we will begin to explore ways to implement state transfer among proxies/orderers.

**Comment by manxiaqu** [comment]
Thank you for your explanation.

So the method I can use in BFTNode is implementing the function installSnapshot(), getSnapshot() ,appExecuteBatch() ,appExecuteUnordered(). And the installSnapshot() and getSnapshot() will be used in deserialise/serialize. 

And, The replica reconnected i referered to is not a reconfiguration but a restart when it down for some time. In this suitation, will it Synchronize to state of the other replica?  And if will, there is a way to get the state or command before through the state transfer protocol, but it is only a internally method used by the library and can't be used by BFTNode.

Am i understand correctly?

And the thing you mentioned above that you are currently working on adding functionality to support what i said first time.  is it on the hyperledger-bftsmart level or the bft-smart/library level? Can you give me directions about your working to add support for it.

**Comment by jcs47** [comment]
> So the method I can use in BFTNode is implementing the function installSnapshot(), getSnapshot() ,appExecuteBatch() ,appExecuteUnordered(). And the installSnapshot() and getSnapshot() will be used in deserialise/serialize.

Yes, exactly, but noticed that all those methods are already implemented by BFTnode. You don't need to implement them all over again.

> The replica reconnected i referered to is not a reconfiguration but a restart when it down for some time. In this suitation, will it Synchronize to state of the other replica? 

Oh yeah, if all you are doing is re-starting a replica that has always been part of the original view, yeah, everything should work fine. The problem is if you try adding a whole new replica to the system, but as I said earlier, the next commits will fix that.

> And if will, there is a way to get the state or command before through the state transfer protocol, but it is only a internally method used by the library and can't be used by BFTNode.

Yes, that is correct.

> And the thing you mentioned above that you are currently working on adding functionality to support what i said first time. is it on the hyperledger-bftsmart level or the bft-smart/library level? Can you give me directions about your working to add support for it.

It will be at the hyperledger-bftsmart level and probably also at the HLF level, The first thing we'll need to do is to had funcionality at the replicas to be notified about new proxies. Following this, we'll need to create a way for proxies to learn what was the last block transmitted by the replicas to the set of proxies (because otherwise they would be expecting the genesis block, which would never arrive). After this, we will need to find a way to transfer the state maintained by orderers, but currently we don't know yet how much built-in supporter there is to acomplish this task.

**Comment by manxiaqu** [comment]
I got it, Thank you ,this is very helpful for my work!
