### ISSUE TITLE
Error in create channel 

### ISSUE THREAD

**Issue by HaoJiawang** [jcs47/hyperledger-bftsmart#51]
I copied the configtx.yaml to container. When I run
`peer channel create -o bft.frontend.1000:7050 -c channel47 -f channel.tx`
Error occurs 
`Error: failed to create deliver client: orderer client failed to connect to bft.frontend.1000:7050: failed to create new connection: context deadline exceeded`
The result of `docker ps ` is shown below, so I am sure order contain is running.
```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
1ad3bd265c99        bftsmart/fabric-tools:amd64-1.3.0          "/bin/bash"              11 minutes ago      Up 11 minutes                           sharp_yonath
08a580a2184e        hyperledger/fabric-peer:amd64-1.3.0        "peer node start"        12 minutes ago      Up 11 minutes                           0.peer.lasige.bft
2cd5a43530af        bftsmart/fabric-frontend:amd64-1.3.0       "./startFrontend.sh …"   12 minutes ago      Up 12 minutes                           1000.frontend.bft
1bd4e0b74d5b        bftsmart/fabric-orderingnode:amd64-1.3.0   "./startReplica.sh 3"    12 minutes ago      Up 12 minutes                           3.node.bft
9430e0801f0c        bftsmart/fabric-orderingnode:amd64-1.3.0   "./startReplica.sh 2"    13 minutes ago      Up 13 minutes                           2.node.bft
babc0a9222da        bftsmart/fabric-orderingnode:amd64-1.3.0   "./startReplica.sh 1"    13 minutes ago      Up 13 minutes                           1.node.bft
2b4e7f54b0fd        bftsmart/fabric-orderingnode:amd64-1.3.0   "./startReplica.sh 0"    13 minutes ago      Up 13 minutes                           0.node.bft
```

**Comment by HaoJiawang** [comment]
In configtx.yaml, `Profiles: Orderer->Addresses`, I write 
```
Addresses:
                - 1000.frontend.bft:7050
                - 2000.frontend.bft:7050
```
should I give actual ip addresses?

**Comment by jcs47** [comment]
Do you also re-generate the genesis block and re-start the whole system? Editing configtx.yaml won't do any good just by itself, because those parameters are read from the genesis block, which is created using the contents of configtx.yaml.

**Comment by HaoJiawang** [comment]
@jcs47 I forget to re-generate the genesis.block. Now, I re-generated it and copied it to order nodes and frontend nodes, but, this problem is not solved.

**Comment by jcs47** [comment]
Have you deleted the peers' state that is stored to disk (by default in the `/bar/hyperledger/production` direvtory) and also copied the genesis file to both the frontends and ordering nodes?

**Comment by HaoJiawang** [comment]
I deleted 2 folders under `production`. Does it mean that I have deleted peers' state that is stored to disk? The problem is not solved yet.
When I run peer container, I found warns:
```
2018-12-27 12:48:52.164 UTC [nodeCmd] createChaincodeServer -> WARN 00c peer.chaincodeListenAddress is not set, using 172.17.0.2:7052
2018-12-27 12:48:52.172 UTC [gossip/gossip] NewGossipService -> WARN 013 External endpoint is empty, peer will not be accessible outside of its organization
```
Does it matter？ Besides that, how can I  configure 4 peer containers' addresses in `core.yaml` ?
I write endpoint and bootstrap to 
 ```
                   - 0.peer.lasige.bft:7051
                   - 1.peer.lasige.bft:7051
                   - 0.peer.ibm.bft:7051
                   - 1.peer.ibm.bft:7051
```
but it shows 
```
2018-12-27 12:48:55.173 UTC [gossip/discovery] func1 -> WARN 020 Could not connect to {1.peer.ibm.bft:7051 [] [] 1.peer.ibm.bft:7051 <nil> <nil>} : context deadline exceeded
2018-12-27 12:48:55.174 UTC [gossip/discovery] func1 -> WARN 021 Could not connect to {1.peer.lasige.bft:7051 [] [] 1.peer.lasige.bft:7051 <nil> <nil>} : context deadline exceeded
2018-12-27 12:48:55.174 UTC [gossip/discovery] func1 -> WARN 022 Could not connect to {0.peer.ibm.bft:7051 [] [] 0.peer.ibm.bft:7051 <nil> <nil>} : context deadline exceed
```

**Comment by jcs47** [comment]
>I deleted 2 folders under production. Does it mean that I have deleted peers' state that is stored to disk? 

That is correct, but I am assuming that you are executing a test-run, so that shouldn't be a concern. The alternative would be to create a configuration transaction, but under the current Fabric codebase, doing that is a hugh assle. But if you want to look into it, you should check this link:

https://hyperledger-fabric.readthedocs.io/en/release-1.3/channel_update_tutorial.html

>The problem is not solved yet.

The last thing it occurs to me is that you might need to edit the `General>listenAddress` parameter in the `orderer.yaml` file. It might be set to 127.0.0.1, and it is advisable to set it to 0.0.0.0. If that doesn't work, or it is already done, than I am clueless to what is causing this issue.

> When I run peer container, I found warns:

Never ran into any problems related to those warnings. But if you want to get rid of them, you should edit `gossip>externalEndpoint` in core.yaml.

>  Besides that, how can I configure 4 peer containers' addresses in core.yaml ?

In my experience, you do not need to pass the complete list of peers to each one. From what I understand of Fabric, each peers fetches the ledger for the channels it is a part of from the ordering service, not from the peer network. I am not 100% sure about this, though.
