### ISSUE TITLE
HLF 1.4 Compatibility?

### ISSUE THREAD

**Issue by dcrough-ownum** [jcs47/hyperledger-bftsmart#57]
Thank you for all your work on this project. Is there a plan and/or a schedule for Fabric 1.4 compatibility of this project?

**Comment by jcs47** [comment]
We are glad you find this project useful. However, there is no plan or schedule to update this ordering service for Fabric 1.4 at least until the beginning of April, because we currently have other stuff we have to finish. Furthermore, this is the absolute best case scenario, because we already have new  projects in the pipeline, and not enough human resources to allocate to this ordering service in a regular basis.

**Comment by dcrough-ownum** [comment]
Thanks @jcs47 -- completely understood and appreciate the information!
