### ISSUE TITLE
Can the proxy know that if two replicas down?

### ISSUE THREAD

**Issue by manxiaqu** [jcs47/hyperledger-bftsmart#7]
I start four replicas(), proxy, orderer, and send some request to replicas, they are in the same state now. Then If two of the replicas down, can the proxy know that?  And in this situation, restart the replicas, can they back to the same state and work well?

**Comment by jcs47** [comment]
When you set up a system comprised by 4 replicas, you can only tolerate a single faulty replica. If you take down 2 replicas, you violate the assumptions adopted by the underlying replication algorithm, therefore the system halts its execution as a consequence of that. You also can't make the service resume execution after those 2 replicas return either, because the state transfer protocol needs to probe 3 replicas to correctly discover the most up-to-date state. In the scenario you describe, there are only 2 replicas to probe, since one is recovering but lost its state, and the other one is still down.

As for the proxy being aware about crashed replicas, it can't really know that either. In the system model for which the BFT-SMaRt library was created for (the partially sinchronous model), individual processes are unable to distinguish a slow replica from a crashed replica.

**Comment by manxiaqu** [comment]
Is there any situation can the replicas back to state when its faulty replicas out of its' set.
I notice that there is a "system.totalordermulticast.log_to_disk" in system.config, it will save the state to disk when i set it true. so in this situation, when a faulty replica restarted, will it back to the state before.? And can it solve the problem above?(and if the BFTNode implement "bftsmart.tom.server.defaultservices.durability.DurabilityCoordinator", will the result change)

**Comment by jcs47** [comment]
That option is intended to avoid the library from consuming to much memory when managing the checkpoints for the state transfer. Furthermore, DurabilityCoordinator is intended to provide an efficient way to store the state to disk, and it isn't as stable as DefaultRecoverable.

Nonetheless, BFT-SMaRt was never designed or tested to recover from a state where the theoretical limit of faults is exceeded, even if the _log_to_disk option is active. I just ran a quick test to see if that situation works by any chance, and it doesn't. The system will halt, the remaining replicas will try to perform a leader election, and even if one of the crashed replicas come back, it is unable to participate in the leader election.

**Comment by manxiaqu** [comment]
I get it.
